### PR TITLE
Pass TEMPLATES along to docker, staging & production instances

### PR DESCRIPTION
**Pull request by sdreher**
"have to pull in anything that we'll be changing"

### CODE REVIEW

**Review by thraxil — COMMENTED** [review]
this would be a non-backwards compatible change. every application using ccnmtlsettings would have to update its `settings_*.py` files

**Comment by sdreher** [comment]
Introduced checking for the TEMPLATES variable before referencing. This should make the code backwards compatible.

**Comment by sdreher** [comment]
Noting: traditionally, we've kept DEBUG & TEMPLATE_DEBUG = True in shared. With the recent TEMPLATE settings changes, another option is to leave debug false and just override in local settings as needed.

**Comment by thraxil** [comment]
Yeah, I'd opt for just defaulting the `TEMPLATE_DEBUG` equivalent to `True` and letting it be overridden in `local_settings.py` if needed.

**Comment by sdreher** [comment]
Okay, I'm going to close this PR. Revert [this commit](https://github.com/ccnmtl/ccnmtlsettings/pull/16). and delete the 1.1.3 release. That should put everything back in place.

**Pull request closed without merging**
